test_ecran : main_test.c dessin_fct.c dessin_fct.c options.h vector.c signed_distance_function.c utiles.c light.c scene.c 3d_obj/*.c
	gcc main_test.c dessin_fct.c vector.c utiles.c signed_distance_function.c light.c scene.c 3d_obj/*.c -O3 -lm -lglfw -lGL -o test_ecran
	
