#ifndef SIMPSONS_H 
#define SIMPSONS_H 

#include "options.h"
#include "utiles.h"
#include "vector.h"
#include "signed_distance_function.h"
#include "objets.h"
#include "bvh.h"

BVHNode* BVH_Book1();
BVHNode* BVH_Book2();
BVHNode* BVH_Book3();
BVHNode* BVH_Book4();
BVHNode* BVH_Book5();
BVHNode* BVH_Book6();
BVHNode* BVH_Book7();
BVHNode* BVH_Book8();
BVHNode* BVH_Book9();
BVHNode* BVH_Book10();
BVHNode* BVH_Book11();
BVHNode* BVH_Book12();
BVHNode* BVH_Book13();
BVHNode* BVH_Book14();
BVHNode* BVH_Book15();
BVHNode* BVH_Book16();
BVHNode* BVH_Book17();
BVHNode* BVH_Book18();
BVHNode* BVH_Book19();
BVHNode* BVH_Cadre_1_Clou();
BVHNode* BVH_Cadre_1_Contour();
BVHNode* BVH_Cadre_1_Corde();
BVHNode* BVH_Cadre_1_Image();
BVHNode* BVH_Cadre_2_Contour();
BVHNode* BVH_Cadre_2_Image();
BVHNode* BVH_Canape_Bras();
BVHNode* BVH_Canape_Dos();
BVHNode* BVH_Canape_Pouf1();
BVHNode* BVH_Canape_Pouf2();
BVHNode* BVH_Canape_Pouf3();
BVHNode* BVH_Canape_Pouf4();
BVHNode* BVH_Canape_Pouf5();
BVHNode* BVH_Canape_Pouf6();
BVHNode* BVH_Canape_Sol();
BVHNode* BVH_Chaise_Pouf();
BVHNode* BVH_Chaise();
BVHNode* BVH_Commode();
BVHNode* BVH_Corbeille_Barro1();
BVHNode* BVH_Corbeille_Barro2();
BVHNode* BVH_Corbeille_Barro3();
BVHNode* BVH_Corbeille_Barro4();
BVHNode* BVH_Corbeille_Barro5();
BVHNode* BVH_Corbeille_Pied();
BVHNode* BVH_Corbeille();
BVHNode* BVH_Lampe_3_Abajour();
BVHNode* BVH_Lampe_3_Abajour2();
BVHNode* BVH_Lampe_3_Abajour3();
BVHNode* BVH_Lampe_3_Pied();
BVHNode* BVH_Lampe_3_Tige();
BVHNode* BVH_Lampe_3_Tige2();
BVHNode* BVH_Lampe_3_Tige3();
BVHNode* BVH_Lampe1_Abajour();
BVHNode* BVH_Lampe1_Abajour2();
BVHNode* BVH_Lampe1_Pied();
BVHNode* BVH_Lampe1_Pied2();
BVHNode* BVH_Lampe2_Abajour();
BVHNode* BVH_Lampe2_Abajour2();
BVHNode* BVH_Lampe2_Pied();
BVHNode* BVH_Mur_Haut();
BVHNode* BVH_Mur();
BVHNode* BVH_Mur1();
BVHNode* BVH_Mur2();
BVHNode* BVH_Mur3();
BVHNode* BVH_PoutreSol();
BVHNode* BVH_Skate_Planche();
BVHNode* BVH_Skate_PorteRoue();
BVHNode* BVH_Skate_Roue();
BVHNode* BVH_Sol();
BVHNode* BVH_Sol2();
BVHNode* BVH_Table_Haut();
BVHNode* BVH_Table_Pied();
BVHNode* BVH_Table();
BVHNode* BVH_Tapis_Centre();
BVHNode* BVH_Tapis_Centre2();
BVHNode* BVH_Tapis_Centre3();
BVHNode* BVH_Tapis_Centre4();
BVHNode* BVH_Telephone_Bouton1();
BVHNode* BVH_Telephone_Bouton2();
BVHNode* BVH_Telephone_Bouton3();
BVHNode* BVH_Telephone_Bouton4();
BVHNode* BVH_Telephone_Bouton5();
BVHNode* BVH_Telephone_Bouton6();
BVHNode* BVH_Telephone_Bouton7();
BVHNode* BVH_Telephone_Bouton8();
BVHNode* BVH_Telephone_Bouton9();
BVHNode* BVH_Telephone_Socle();
BVHNode* BVH_Telephone_Tel();
BVHNode* BVH_Trombone_Bout();
BVHNode* BVH_Trombone_Bouton1();
BVHNode* BVH_Trombone_Bouton2();
BVHNode* BVH_Trombone_Bouton3();
BVHNode* BVH_Trombone_Bouton4();
BVHNode* BVH_Trombone_Bouton5();
BVHNode* BVH_Trombone_Bouton6();
BVHNode* BVH_Trombone_Bouton7();
BVHNode* BVH_Trombone_Bouton8();
BVHNode* BVH_Trombone_Bouton9();
BVHNode* BVH_Trombone_Bouton10();
BVHNode* BVH_Trombone_Bouton11();
BVHNode* BVH_Trombone_Bouton12();
BVHNode* BVH_Trombone_Bouton13();
BVHNode* BVH_Trombone_Bouton14();
BVHNode* BVH_Trombone();
BVHNode* BVH_VraiSol();

BVHNode* BVH_Books();
BVHNode* BVH_FullCanape();
BVHNode* BVH_FullTrombone();
BVHNode* BVH_CanapeTrombone();
BVHNode* BVH_AllMurs();
BVHNode* BVH_MurCanap();
BVHNode* BVH_AllLampes();
BVHNode* BVH_Tapis();
BVHNode* BVH_Sols();
BVHNode* BVH_FullCorbeille();
BVHNode* BVH_Cadres();
BVHNode* BVH_ChaiseTable();
BVHNode* BVH_Maison();




#endif